package com.epul.cerisaie.hibernate.metier;

// Generated 3 juin 2015 10:21:18 by Hibernate Tools 4.3.1


import java.util.*;


import javax.persistence.*;

/**
 * Apprenant generated by hbm2java
 */
@Entity
@Table(name = "apprenant", catalog = "permispiste")
public class Apprenant implements java.io.Serializable {

    private int numapprenant;
    private String nomapprenant;
    private String prenomapprenant;
    List<Obtient> mesResultats = new ArrayList<Obtient>();
    List<Jeu> monJeu = new ArrayList<Jeu>();

    public Apprenant() {
    }

    public Apprenant(int numapprenant) {
        this.numapprenant = numapprenant;
    }

    public Apprenant(int numapprenant, String nomapprenant,
                     String prenomapprenant, List<Obtient> obtients) {
        this.numapprenant = numapprenant;
        this.nomapprenant = nomapprenant;
        this.prenomapprenant = prenomapprenant;
        this.mesResultats = obtients;
    }

    @Id
    @Column(name = "NUMAPPRENANT", unique = true, nullable = false)
    public int getNumapprenant() {
        return this.numapprenant;
    }

    public void setNumapprenant(int numapprenant) {
        this.numapprenant = numapprenant;
    }

    @Column(name = "NOMAPPRENANT", length = 25)
    public String getNomapprenant() {
        return this.nomapprenant;
    }

    public void setNomapprenant(String nomapprenant) {
        this.nomapprenant = nomapprenant;
    }

    @Column(name = "PRENOMAPPRENANT", length = 25)
    public String getPrenomapprenant() {
        return this.prenomapprenant;
    }

    public void setPrenomapprenant(String prenomapprenant) {
        this.prenomapprenant = prenomapprenant;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "apprenant")
    public List<Obtient> getObtients() {
        return this.mesResultats;
    }

    public void setObtients(List<Obtient> obtients) {
        this.mesResultats = obtients;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "inscrit", catalog = "permispiste", joinColumns = { @JoinColumn(name = "NUMAPPRENANT", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "NUMJEU", nullable = false, updatable = false) })
    public List<Jeu> getMonJeu() {
        return monJeu;
    }

    public void setMonJeu(List<Jeu> monJeu) {
        this.monJeu = monJeu;
    }
}
