package com.epul.projetpiste.hibernate.metier;

// Generated 3 juin 2015 10:21:18 by Hibernate Tools 4.3.1

import javax.persistence.*;

/**
 * Obtient generated by hbm2java
 */
@Entity
@Table(name = "inscrit", catalog = "permispiste")
public class Inscrit implements java.io.Serializable {

    private InscritId id;
    private Jeu jeu;
    private Apprenant apprenant;
    private Calendrier calendrier;

    public Inscrit() {
    }

    public Inscrit(InscritId id, Jeu jeu, Apprenant apprenant,
                   Calendrier calendrier) {
        this.id = id;
        this.jeu = jeu;
        this.apprenant = apprenant;
        this.calendrier = calendrier;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "numjeu", column = @Column(name = "NUMJEU", nullable = false)),
            @AttributeOverride(name = "numapprenant", column = @Column(name = "NUMAPPRENANT", nullable = false)),
            @AttributeOverride(name = "datejour", column = @Column(name = "DATEJOUR", nullable = false, length = 10))})
    public InscritId getId() {
        return this.id;
    }

    public void setId(InscritId id) {
        this.id = id;
    }


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NUMJEU", nullable = false, insertable = false, updatable = false)
    public Jeu getJeu() {
        return jeu;
    }

    public void setJeu(Jeu jeu) {
        this.jeu = jeu;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NUMAPPRENANT", nullable = false, insertable = false, updatable = false)
    public Apprenant getApprenant() {
        return this.apprenant;
    }

    public void setApprenant(Apprenant apprenant) {
        this.apprenant = apprenant;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "DATEJOUR", nullable = false, insertable = false, updatable = false)
    public Calendrier getCalendrier() {
        return this.calendrier;
    }

    public void setCalendrier(Calendrier calendrier) {
        this.calendrier = calendrier;
    }

}
