package com.epul.projetpiste.hibernate.metier;

// Generated 3 juin 2015 10:21:18 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObtientId generated by hbm2java
 */
@Embeddable
public class InscritId implements java.io.Serializable {

    private int numjeu;
    private int numapprenant;
    private Date datejour;

    public InscritId() {
    }

    public InscritId(int numjeu, int numapprenant, Date datejour) {
        this.numjeu = numjeu;
        this.numapprenant = numapprenant;
        this.datejour = datejour;
    }

    @Column(name = "NUMJEU", nullable = false)
    public int getNumjeu() {
        return this.numjeu;
    }

    public void setNumjeu(int numjeu) {
        this.numjeu = numjeu;
    }

    @Column(name = "NUMAPPRENANT", nullable = false)
    public int getNumapprenant() {
        return this.numapprenant;
    }

    public void setNumapprenant(int numapprenant) {
        this.numapprenant = numapprenant;
    }

    @Column(name = "DATEJOUR", nullable = false, length = 10)
    public Date getDatejour() {
        return this.datejour;
    }

    public void setDatejour(Date datejour) {
        this.datejour = datejour;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof InscritId))
            return false;
        InscritId castOther = (InscritId) other;

        return (this.getNumapprenant() == castOther.getNumapprenant())
                && ((this.getDatejour() == castOther.getDatejour()) || (this
                .getDatejour() != null
                && castOther.getDatejour() != null && this
                .getDatejour().equals(castOther.getDatejour())))
                && (this.getNumjeu() == castOther.getNumjeu());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getNumapprenant();
        result = 37 * result
                + (getDatejour() == null ? 0 : this.getDatejour().hashCode());
        result = 37 * result + this.getNumjeu();
        return result;
    }

}
